name: Build Clock

on:
  push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: Homebrew/actions/setup-homebrew@master
        run: |
          brew install arduino-cli

      - name: Create TMPDIR
        run : |
          export TMPDIR=$(mktemp -d)

      - name: Install sketch dependencies
        run: |
          make install

      - name: Build sketch
        run: |
          make build
